{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pair",
    "query": "SELECT symbol FROM pairs ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "فرصت های اخر",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  o.detected_at AS detected_at,\r\n  p.symbol      AS pair,\r\n  be.name       AS buy_exchange,\r\n  se.name       AS sell_exchange,\r\n  o.diff_abs    AS diff_abs,\r\n  (o.diff_pct * 100.0) AS diff_pct\r\nFROM opportunities o\r\nJOIN pairs p     ON p.id  = o.pair_id\r\nJOIN exchanges be ON be.id = o.buy_exchange_id\r\nJOIN exchanges se ON se.id = o.sell_exchange_id\r\nWHERE p.symbol = '$pair'\r\n  AND $__timeFilter(o.detected_at)\r\nORDER BY o.detected_at DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "آخرین قیمت هر صرافی",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (e.id)\r\n  e.name       AS exchange,\r\n  p.symbol     AS pair,\r\n  t.price      AS price,\r\n  t.fetched_at AS fetched_at\r\nFROM ticks t\r\nJOIN exchanges e ON e.id = t.exchange_id\r\nJOIN pairs p     ON p.id = t.pair_id\r\nWHERE p.symbol = '$pair'\r\nORDER BY e.id, t.fetched_at DESC;\r\n"
    }
   ]
  },
  {
   "title": "قیمت هر صرافی",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  t.fetched_at AS \"time\",\r\n  e.name || ' ' || p.symbol AS metric,\r\n  t.price AS value\r\nFROM ticks t\r\nJOIN exchanges e ON e.id = t.exchange_id\r\nJOIN pairs p     ON p.id = t.pair_id\r\nWHERE p.symbol = '$pair'\r\n  AND $__timeFilter(t.fetched_at)\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "تعداد فرصت‌های آربیتراژ در زمان",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', o.detected_at) - \r\n    (EXTRACT(MINUTE FROM o.detected_at)::int % 5) * interval '1 minute'\r\n    AS \"time\",\r\n  count(*)::int AS value\r\nFROM opportunities o\r\nJOIN pairs p ON p.id = o.pair_id\r\nWHERE p.symbol = '$pair'\r\n  AND $__timeFilter(o.detected_at)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "میانگین درصد سود در زمان",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', o.detected_at)\r\n  - (EXTRACT(MINUTE FROM o.detected_at)::int % 5) * interval '1 minute' AS \"time\",\r\n  AVG(o.diff_pct) * 100.0 AS value\r\nFROM opportunities o\r\nJOIN pairs p ON p.id = o.pair_id\r\nWHERE p.symbol = '$pair'\r\n  AND $__timeFilter(o.detected_at)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}