{
 "title": "New dashboard2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "transfer per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=~\"$db\"}[5m]) + rate(pg_stat_database_xact_rollback{datname=~\"$db\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "حجم دیتابیس",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"$db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Health",
   "type": "timeseries",
   "description": "باید ۰ باشد؛ اگر ۱ شد یعنی exporter نتوانسته کوئری‌ها را بخواند.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_error\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "تعداد اتصال‌های فعال",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_database_numbackends{datname=~\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}